# Generated by Django 4.2.21 on 2025-05-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='FIO')),
                ('info', models.TextField(verbose_name='Biography')),
                ('photo', models.ImageField(upload_to='photo /%Y/%m/%b', verbose_name='Photo')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
    ]
