# Generated by Django 4.2.21 on 2025-05-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_helps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helplist',
            name='info',
        ),
        migrations.AlterField(
            model_name='helplist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Commercial name'),
        ),
        migrations.AlterField(
            model_name='helplist',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y/%m/%b', verbose_name='Photo'),
        ),
    ]
