# Generated by Django 4.2.21 on 2025-05-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_helps', '0002_remove_helplist_info_alter_helplist_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('photos', models.ImageField(upload_to='photo/%Y/%m/%b', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Промо-блок',
                'verbose_name_plural': 'Промо-блоки',
            },
        ),
    ]
