# Generated by Django 4.2.21 on 2025-05-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_helps', '0003_promoblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promoblock',
            old_name='photos',
            new_name='phototutor',
        ),
    ]
