# Generated by Django 4.2.21 on 2025-05-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_helps', '0005_bannerblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('phototutor', models.ImageField(upload_to='photo/%Y/%m/%b', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Спонсор-блок',
                'verbose_name_plural': 'Спонсор-блоки',
            },
        ),
        migrations.AlterField(
            model_name='bannerblock',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='helplist',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Commercial name'),
        ),
        migrations.AlterField(
            model_name='promoblock',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок'),
        ),
    ]
