# Generated by Django 4.2.21 on 2025-05-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_helps', '0006_sponsorblock_alter_bannerblock_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorblock',
            name='description',
        ),
    ]
