# Generated by Django 4.2.21 on 2025-05-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_helps', '0007_remove_sponsorblock_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('phototutor', models.ImageField(upload_to='photo/%Y/%m/%b', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Заказ-блок',
                'verbose_name_plural': 'Заказ-блоков',
            },
        ),
    ]
