# Generated by Django 4.2.21 on 2025-06-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_helps', '0009_productblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productblock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productblock',
            name='title',
        ),
    ]
