# Generated by Django 4.2.21 on 2025-06-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_helps', '0010_remove_productblock_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBlock2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('phototutor', models.ImageField(upload_to='photo/%Y/%m/%b', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Продукт-блок',
                'verbose_name_plural': 'Продукт-блоки',
            },
        ),
        migrations.CreateModel(
            name='ProductBlock3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('phototutor', models.ImageField(upload_to='photo/%Y/%m/%b', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Продукт-блок',
                'verbose_name_plural': 'Продукт-блоки',
            },
        ),
        migrations.CreateModel(
            name='ProductBlock4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('phototutor', models.ImageField(upload_to='photo/%Y/%m/%b', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Продукт-блок',
                'verbose_name_plural': 'Продукт-блоки',
            },
        ),
    ]
