# Generated by Django 4.2.21 on 2025-06-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_helps', '0011_productblock2_productblock3_productblock4'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productblock2',
            options={'verbose_name': 'Продукт-блок2', 'verbose_name_plural': 'Продукт-блоки2'},
        ),
        migrations.AlterModelOptions(
            name='productblock3',
            options={'verbose_name': 'Продукт-блок3', 'verbose_name_plural': 'Продукт-блоки3'},
        ),
        migrations.AlterModelOptions(
            name='productblock4',
            options={'verbose_name': 'Продукт-блок4', 'verbose_name_plural': 'Продукт-блоки4'},
        ),
    ]
