# Generated by Django 4.2.21 on 2025-06-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_helps', '0012_alter_productblock2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productblock',
            name='title',
            field=models.CharField(default='Без названия', max_length=1000, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='productblock2',
            name='title',
            field=models.CharField(default='Без названия', max_length=1000, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='productblock3',
            name='title',
            field=models.CharField(default='Без названия', max_length=1000, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='productblock4',
            name='title',
            field=models.CharField(default='Без названия', max_length=1000, verbose_name='Заголовок'),
        ),
    ]
